// API adapter for web and electron environments
const isElectron = typeof window !== 'undefined' && window.electronAPI;

const api = isElectron ? {
  // Electron APIs
  login: (credentials) => window.electronAPI?.invoke('auth:login', credentials),
  auth: {
    registerMerchant: (data) => window.electronAPI?.invoke('auth:register-merchant', data),
  },
  inventory: {
    getAll: (storeId) => window.electronAPI?.invoke('inventory:get-all', storeId),
    add: (product) => window.electronAPI?.invoke('inventory:add', product),
    import: (data) => window.electronAPI?.invoke('inventory:import', data),
    update: (product) => window.electronAPI?.invoke('inventory:update', product),
    delete: (data) => window.electronAPI?.invoke('inventory:delete', data),
  },
  sales: {
    create: (data) => window.electronAPI?.invoke('sales:create', data),
  },
  customers: {
    getAll: (data) => window.electronAPI?.invoke('customers:get-all', data),
    add: (data) => window.electronAPI?.invoke('customers:add', data),
    update: (data) => window.electronAPI?.invoke('customers:update', data),
    delete: (data) => window.electronAPI?.invoke('customers:delete', data),
  },
  expenses: {
    getAll: (storeId) => window.electronAPI?.invoke('expenses:get-all', storeId),
    add: (data) => window.electronAPI?.invoke('expenses:add', data),
    delete: (data) => window.electronAPI?.invoke('expenses:delete', data),
  },
  reports: {
    getDashboard: (storeId) => window.electronAPI?.invoke('reports:dashboard', storeId),
    getNetProfit: (data) => window.electronAPI?.invoke('reports:net-profit', data),
    getInventoryValue: (storeId) => window.electronAPI?.invoke('reports:inventory-value', storeId),
    getSalesVsPurchases: (data) => window.electronAPI?.invoke('reports:sales-vs-purchases', data),
    getExpensesByCategory: (storeId) => window.electronAPI?.invoke('reports:expenses-by-category', storeId),
    getFinancialAlerts: (storeId) => window.electronAPI?.invoke('reports:financial-alerts', storeId),
  },
  duePayments: {
    getAll: (storeId) => window.electronAPI?.invoke('due-payments:get-all', storeId),
    add: (data) => window.electronAPI?.invoke('due-payments:add', data),
    update: (data) => window.electronAPI?.invoke('due-payments:update', data),
    delete: (data) => window.electronAPI?.invoke('due-payments:delete', data),
  },
  rents: {
    getAll: (storeId) => window.electronAPI?.invoke('rents:get-all', storeId),
    add: (data) => window.electronAPI?.invoke('rents:add', data),
    update: (data) => window.electronAPI?.invoke('rents:update', data),
    delete: (data) => window.electronAPI?.invoke('rents:delete', data),
    items: {
      getAll: (storeId) => window.electronAPI?.invoke('rents:items:get-all', storeId),
      add: (data) => window.electronAPI?.invoke('rents:items:add', data),
      delete: (data) => window.electronAPI?.invoke('rents:items:delete', data),
    },
  },
  hr: {
    getPresences: (storeId) => window.electronAPI?.invoke('hr:get-presences', storeId),
    checkIn: (data) => window.electronAPI?.invoke('hr:check-in', data),
    getSalaries: (storeId) => window.electronAPI?.invoke('hr:get-salaries', storeId),
    generateSalary: (data) => window.electronAPI?.invoke('hr:generate-salary', data),
    getUsers: (storeId) => window.electronAPI?.invoke('hr:get-users', storeId),
    addUser: (data) => window.electronAPI?.invoke('hr:add-user', data),
  },
  store: {
    get: (storeId) => window.electronAPI?.invoke('store:get', storeId),
    save: (data) => window.electronAPI?.invoke('store:save', data),
    uploadLogo: (data) => window.electronAPI?.invoke('store:upload-logo', data),
    requests: {
      getAll: () => window.electronAPI?.invoke('store:requests:get-all'),
      add: (data) => window.electronAPI?.invoke('store:requests:add', data),
      updateStatus: (id, status) => window.electronAPI?.invoke('store:requests:update-status', id, status),
    },
  },
  stores: {
    getBySlug: (slug) => window.electronAPI?.invoke('stores:get-by-slug', slug),
    getById: (id) => window.electronAPI?.invoke('stores:get-by-id', id),
    getMerchantStores: (merchantId) => window.electronAPI?.invoke('stores:get-merchant-stores', merchantId),
    create: (data) => window.electronAPI?.invoke('stores:create', data),
    update: (data) => window.electronAPI?.invoke('stores:update', data),
    delete: (id) => window.electronAPI?.invoke('stores:delete', id),
    updateSubscription: (data) => window.electronAPI?.invoke('stores:update-subscription', data),
    getAll: () => window.electronAPI?.invoke('stores:get-all'),
  },
  customerAuth: {
    register: (data) => window.electronAPI?.invoke('customer-auth:register', data),
    login: (credentials) => window.electronAPI?.invoke('customer-auth:login', credentials),
    approve: (customerId) => window.electronAPI?.invoke('customer-auth:approve', customerId),
    reject: (customerId) => window.electronAPI?.invoke('customer-auth:reject', customerId),
  },
  customerPortal: {
    getStores: (customerId) => window.electronAPI?.invoke('customer-portal:get-stores', customerId),
    getStoreDetails: (data) => window.electronAPI?.invoke('customer-portal:get-store-details', data),
    requestBalance: (data) => window.electronAPI?.invoke('customer-portal:request-balance', data),
    getTransactions: (data) => window.electronAPI?.invoke('customer-portal:get-transactions', data),
    getProducts: (storeId) => window.electronAPI?.invoke('customer-portal:get-products', storeId),
    getOffers: (storeId) => window.electronAPI?.invoke('customer-portal:get-offers', storeId),
    getInvoices: (data) => window.electronAPI?.invoke('customer-portal:get-invoices', data),
    getPendingOrders: (storeId) => window.electronAPI?.invoke('customer-portal:get-pending-orders', storeId),
    convertOrderToInvoice: (orderId) => window.electronAPI?.invoke('customer-portal:convert-order-to-invoice', orderId),
    getOrders: (data) => window.electronAPI?.invoke('customer-portal:get-orders', data),
    createOrder: (data) => window.electronAPI?.invoke('customer-portal:create-order', data),
  },
  customerBalance: {
    getRequests: (storeId) => window.electronAPI?.invoke('customer-balance:get-requests', storeId),
    approve: (data) => window.electronAPI?.invoke('customer-balance:approve', data),
    reject: (requestId) => window.electronAPI?.invoke('customer-balance:reject', requestId),
  },
  categories: {
    getAll: (storeId) => window.electronAPI?.invoke('categories:get-all', storeId),
    add: (data) => window.electronAPI?.invoke('categories:add', data),
    update: (data) => window.electronAPI?.invoke('categories:update', data),
    delete: (data) => window.electronAPI?.invoke('categories:delete', data),
  },
  purchases: {
    getAll: (storeId) => window.electronAPI?.invoke('purchases:get-all', storeId),
    create: (data) => window.electronAPI?.invoke('purchases:create', data),
    update: (data) => window.electronAPI?.invoke('purchases:update', data),
    delete: (data) => window.electronAPI?.invoke('purchases:delete', data),
  },
  suppliers: {
    getAll: (storeId) => window.electronAPI?.invoke('suppliers:get-all', storeId),
    add: (data) => window.electronAPI?.invoke('suppliers:add', data),
    update: (data) => window.electronAPI?.invoke('suppliers:update', data),
    delete: (data) => window.electronAPI?.invoke('suppliers:delete', data),
  },
  currencies: {
    getAll: () => window.electronAPI?.invoke('currencies:get-all'),
    getStoreCurrency: (storeId) => window.electronAPI?.invoke('currencies:get-store-currency', storeId),
    convert: (data) => window.electronAPI?.invoke('currencies:convert', data),
  },
  subscriptions: {
    getPlans: () => window.electronAPI?.invoke('subscriptions:get-plans'),
    getStoreRequests: (storeId) => window.electronAPI?.invoke('subscriptions:get-store-requests', storeId),
    createRequest: (data) => window.electronAPI?.invoke('subscriptions:create-request', data),
    getAllPlans: () => window.electronAPI?.invoke('subscriptions:get-all-plans'),
    updatePlan: (id, data) => window.electronAPI?.invoke('subscriptions:update-plan', id, data),
    addPlan: (data) => window.electronAPI?.invoke('subscriptions:add-plan', data),
    deletePlan: (id) => window.electronAPI?.invoke('subscriptions:delete-plan', id),
    getAllRequests: () => window.electronAPI?.invoke('subscriptions:get-all-requests'),
    approveRequest: (requestId, approvedBy) => window.electronAPI?.invoke('subscriptions:approve-request', requestId, approvedBy),
    rejectRequest: (requestId, approvedBy, reason) => window.electronAPI?.invoke('subscriptions:reject-request', requestId, approvedBy, reason),
  },
  platformAdmin: {
    getDashboard: () => window.electronAPI?.invoke('platform-admin:get-dashboard'),
    getAllBalanceRequests: (filters) => window.electronAPI?.invoke('platform-admin:get-all-balance-requests', filters),
    getMerchants: () => window.electronAPI?.invoke('platform-admin:get-merchants'),
    updateMerchantStatus: (data) => window.electronAPI?.invoke('platform-admin:update-merchant-status', data),
    deleteMerchant: (merchantId) => window.electronAPI?.invoke('platform-admin:delete-merchant', merchantId),
    getAllStores: () => window.electronAPI?.invoke('platform-admin:get-all-stores'),
    updateStoreSubscription: (data) => window.electronAPI?.invoke('platform-admin:update-store-subscription', data),
    deleteStore: (storeId) => window.electronAPI?.invoke('platform-admin:delete-store', storeId),
  },
  audit: {
    getLogs: (filters) => window.electronAPI?.invoke('audit:get-logs', filters),
  },
  backup: {
    create: () => window.electronAPI?.invoke('backup:create'),
    restore: (filePath) => window.electronAPI?.invoke('backup:restore', filePath),
  },
  migrations: {
    run: () => window.electronAPI?.invoke('migrations:run'),
  },
  sync: {
    start: () => window.electronAPI?.invoke('sync:start'),
    getStatus: () => window.electronAPI?.invoke('sync:get-status'),
  },
  autoSync: {
    enable: () => window.electronAPI?.invoke('auto-sync:enable'),
    disable: () => window.electronAPI?.invoke('auto-sync:disable'),
  },
  window: {
    openWithLogin: (type, title) => window.electronAPI?.invoke('window:open-with-login', type, title),
  },
} : {
  // Web fallback - these would need to be implemented as HTTP calls to a backend
  login: () => Promise.reject(new Error('Not available in web mode')),
  auth: {
    registerMerchant: () => Promise.reject(new Error('Not available in web mode')),
  },
  inventory: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    import: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  sales: {
    create: () => Promise.reject(new Error('Not available in web mode')),
  },
  customers: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  expenses: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  reports: {
    getDashboard: () => Promise.reject(new Error('Not available in web mode')),
    getNetProfit: () => Promise.reject(new Error('Not available in web mode')),
    getInventoryValue: () => Promise.reject(new Error('Not available in web mode')),
    getSalesVsPurchases: () => Promise.reject(new Error('Not available in web mode')),
    getExpensesByCategory: () => Promise.reject(new Error('Not available in web mode')),
    getFinancialAlerts: () => Promise.reject(new Error('Not available in web mode')),
  },
  duePayments: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  rents: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
    items: {
      getAll: () => Promise.reject(new Error('Not available in web mode')),
      add: () => Promise.reject(new Error('Not available in web mode')),
      delete: () => Promise.reject(new Error('Not available in web mode')),
    },
  },
  hr: {
    getPresences: () => Promise.reject(new Error('Not available in web mode')),
    checkIn: () => Promise.reject(new Error('Not available in web mode')),
    getSalaries: () => Promise.reject(new Error('Not available in web mode')),
    generateSalary: () => Promise.reject(new Error('Not available in web mode')),
    getUsers: () => Promise.reject(new Error('Not available in web mode')),
    addUser: () => Promise.reject(new Error('Not available in web mode')),
  },
  store: {
    get: () => Promise.reject(new Error('Not available in web mode')),
    save: () => Promise.reject(new Error('Not available in web mode')),
    uploadLogo: () => Promise.reject(new Error('Not available in web mode')),
    requests: {
      getAll: () => Promise.reject(new Error('Not available in web mode')),
      add: () => Promise.reject(new Error('Not available in web mode')),
      updateStatus: () => Promise.reject(new Error('Not available in web mode')),
    },
  },
  stores: {
    getBySlug: () => Promise.reject(new Error('Not available in web mode')),
    getById: () => Promise.reject(new Error('Not available in web mode')),
    getMerchantStores: () => Promise.reject(new Error('Not available in web mode')),
    create: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
    updateSubscription: () => Promise.reject(new Error('Not available in web mode')),
    getAll: () => Promise.reject(new Error('Not available in web mode')),
  },
  customerAuth: {
    register: () => Promise.reject(new Error('Not available in web mode')),
    login: () => Promise.reject(new Error('Not available in web mode')),
    approve: () => Promise.reject(new Error('Not available in web mode')),
    reject: () => Promise.reject(new Error('Not available in web mode')),
  },
  customerPortal: {
    getStores: () => Promise.reject(new Error('Not available in web mode')),
    getStoreDetails: () => Promise.reject(new Error('Not available in web mode')),
    requestBalance: () => Promise.reject(new Error('Not available in web mode')),
    getTransactions: () => Promise.reject(new Error('Not available in web mode')),
    getProducts: () => Promise.reject(new Error('Not available in web mode')),
    getOffers: () => Promise.reject(new Error('Not available in web mode')),
    getInvoices: () => Promise.reject(new Error('Not available in web mode')),
    getPendingOrders: () => Promise.reject(new Error('Not available in web mode')),
    convertOrderToInvoice: () => Promise.reject(new Error('Not available in web mode')),
    getOrders: () => Promise.reject(new Error('Not available in web mode')),
    createOrder: () => Promise.reject(new Error('Not available in web mode')),
  },
  customerBalance: {
    getRequests: () => Promise.reject(new Error('Not available in web mode')),
    approve: () => Promise.reject(new Error('Not available in web mode')),
    reject: () => Promise.reject(new Error('Not available in web mode')),
  },
  categories: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  purchases: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    create: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  suppliers: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    add: () => Promise.reject(new Error('Not available in web mode')),
    update: () => Promise.reject(new Error('Not available in web mode')),
    delete: () => Promise.reject(new Error('Not available in web mode')),
  },
  currencies: {
    getAll: () => Promise.reject(new Error('Not available in web mode')),
    getStoreCurrency: () => Promise.reject(new Error('Not available in web mode')),
    convert: () => Promise.reject(new Error('Not available in web mode')),
  },
  subscriptions: {
    getPlans: () => Promise.reject(new Error('Not available in web mode')),
    getStoreRequests: () => Promise.reject(new Error('Not available in web mode')),
    createRequest: () => Promise.reject(new Error('Not available in web mode')),
    getAllPlans: () => Promise.reject(new Error('Not available in web mode')),
    updatePlan: () => Promise.reject(new Error('Not available in web mode')),
    addPlan: () => Promise.reject(new Error('Not available in web mode')),
    deletePlan: () => Promise.reject(new Error('Not available in web mode')),
    getAllRequests: () => Promise.reject(new Error('Not available in web mode')),
    approveRequest: () => Promise.reject(new Error('Not available in web mode')),
    rejectRequest: () => Promise.reject(new Error('Not available in web mode')),
  },
  platformAdmin: {
    getDashboard: () => Promise.reject(new Error('Not available in web mode')),
    getAllBalanceRequests: () => Promise.reject(new Error('Not available in web mode')),
    getMerchants: () => Promise.reject(new Error('Not available in web mode')),
    updateMerchantStatus: () => Promise.reject(new Error('Not available in web mode')),
    deleteMerchant: () => Promise.reject(new Error('Not available in web mode')),
    getAllStores: () => Promise.reject(new Error('Not available in web mode')),
    updateStoreSubscription: () => Promise.reject(new Error('Not available in web mode')),
    deleteStore: () => Promise.reject(new Error('Not available in web mode')),
  },
  audit: {
    getLogs: () => Promise.reject(new Error('Not available in web mode')),
  },
  backup: {
    create: () => Promise.reject(new Error('Not available in web mode')),
    restore: () => Promise.reject(new Error('Not available in web mode')),
  },
  migrations: {
    run: () => Promise.reject(new Error('Not available in web mode')),
  },
  sync: {
    start: () => Promise.reject(new Error('Not available in web mode')),
    getStatus: () => Promise.reject(new Error('Not available in web mode')),
  },
  autoSync: {
    enable: () => Promise.reject(new Error('Not available in web mode')),
    disable: () => Promise.reject(new Error('Not available in web mode')),
  },
  window: {
    openWithLogin: () => Promise.reject(new Error('Not available in web mode')),
  },
};

export default api;